// <auto-generated />
using System;
using DiabloBuildTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiabloBuildTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124215501_SeedBarbarianSkills")]
    partial class SeedBarbarianSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.BuildItem", b =>
                {
                    b.Property<int>("BuildId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("BuildId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BuildItems");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.BuildSkill", b =>
                {
                    b.Property<int>("BuildId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("BuildId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("BuildSkills");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Barbarian"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Druid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Necromancer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rouge"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sorcerer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sprirtborn"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Paladin"
                        });
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("MaxRank")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SkillType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SkillCategoryId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Bash",
                            SkillCategoryId = 1,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Lunging Strike",
                            SkillCategoryId = 1,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Frenzy",
                            SkillCategoryId = 1,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Flay",
                            SkillCategoryId = 1,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Whirlwind",
                            SkillCategoryId = 2,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Hammer of the Ancients",
                            SkillCategoryId = 2,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Upheaval",
                            SkillCategoryId = 2,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Double Swing",
                            SkillCategoryId = 2,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Rend",
                            SkillCategoryId = 2,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Ground Stomp",
                            SkillCategoryId = 3,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 11,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Rallying Cry",
                            SkillCategoryId = 3,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 12,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Iron Skin",
                            SkillCategoryId = 3,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 13,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Challenging Shout",
                            SkillCategoryId = 3,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 14,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Kick",
                            SkillCategoryId = 5,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 15,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "War Cry",
                            SkillCategoryId = 5,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 16,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Charge",
                            SkillCategoryId = 5,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 17,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Leap",
                            SkillCategoryId = 5,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 18,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Rupture",
                            SkillCategoryId = 6,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 19,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Steel Grasp",
                            SkillCategoryId = 6,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 20,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Death Blow",
                            SkillCategoryId = 6,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 21,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Mighty Throw",
                            SkillCategoryId = 6,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 22,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Call Of The Ancients",
                            SkillCategoryId = 8,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 23,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Iron Maelstrom",
                            SkillCategoryId = 8,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 24,
                            ClassId = 1,
                            MaxRank = 5,
                            Name = "Wrath Of The Berserker",
                            SkillCategoryId = 8,
                            SkillType = 1
                        },
                        new
                        {
                            Id = 25,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Pressure Point",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 26,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Endless Cry",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 27,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Warpath",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 28,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Imposing Presence",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 29,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Martial Vigor",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 30,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Outburst",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 31,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Tough As Nails",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 32,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Belligerence",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 33,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Booming Voice",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 34,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Raid Leader",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 35,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Guttural Yell",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 36,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Aggressive Resistance",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 37,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Battle Fervor",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 38,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Prolific Fury",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 39,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Swiftness",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 40,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Quick Impulses",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 41,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "No Mercy",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 42,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Slaying Strike",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 43,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Expose Vulnerability",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 44,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Thick Skin",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 45,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Defensive Stance",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 46,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Counteroffensive",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 47,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Hamstring",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 48,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Cut To The Bone",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 49,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Pit Fighter",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 50,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Irrepressible",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 51,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Heavy Handed",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 52,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Wallop ",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 53,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Brute Force",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 54,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Concussion",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 55,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Tempered Fury",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 56,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Furious Impulse",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 57,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Invigorating Fury",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 58,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Duelist",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 59,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Heavy Hitter",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 60,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Unconstrained",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 61,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Walking Arsenal",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 62,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Unbridled Rage",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 63,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Gushing Wounds",
                            SkillCategoryId = 4,
                            SkillType = 2
                        },
                        new
                        {
                            Id = 64,
                            ClassId = 1,
                            MaxRank = 3,
                            Name = "Barbed Carapace",
                            SkillCategoryId = 4,
                            SkillType = 2
                        });
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.SkillCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkillCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Core"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Defensive"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Passive"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Brawling"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Weapon Mastery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Upgrades"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ultimate"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Key Passive"
                        });
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.SkillUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredUpgradeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillUpgrades");

                    b.HasData(
                        new
                        {
                            Id = 65,
                            Description = "",
                            Name = "Enhanced Bash",
                            RequiredUpgradeId = 0,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 66,
                            Description = "",
                            Name = "Battle Bash",
                            RequiredUpgradeId = 65,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 67,
                            Description = "",
                            Name = "Combat Bash",
                            RequiredUpgradeId = 0,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 68,
                            Description = "",
                            Name = "Enhanced Lunging Strike",
                            RequiredUpgradeId = 0,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 69,
                            Description = "",
                            Name = "Battle Lunging Strike",
                            RequiredUpgradeId = 68,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 70,
                            Description = "",
                            Name = "Combat Lunging Strike",
                            RequiredUpgradeId = 0,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 71,
                            Description = "",
                            Name = "Enhanced Frenzy",
                            RequiredUpgradeId = 0,
                            SkillId = 3
                        },
                        new
                        {
                            Id = 72,
                            Description = "",
                            Name = "Battle Frenzy",
                            RequiredUpgradeId = 71,
                            SkillId = 3
                        },
                        new
                        {
                            Id = 73,
                            Description = "",
                            Name = "Combat Frenzy",
                            RequiredUpgradeId = 0,
                            SkillId = 3
                        },
                        new
                        {
                            Id = 74,
                            Description = "",
                            Name = "Enhanced Flay",
                            RequiredUpgradeId = 0,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 75,
                            Description = "",
                            Name = "Battle Flay",
                            RequiredUpgradeId = 74,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 76,
                            Description = "",
                            Name = "Combat Flay",
                            RequiredUpgradeId = 0,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 77,
                            Description = "",
                            Name = "Enhanced Whirlwind",
                            RequiredUpgradeId = 0,
                            SkillId = 5
                        },
                        new
                        {
                            Id = 78,
                            Description = "",
                            Name = "Furious Whirlwind",
                            RequiredUpgradeId = 77,
                            SkillId = 5
                        },
                        new
                        {
                            Id = 79,
                            Description = "",
                            Name = "Violent Whirlwind",
                            RequiredUpgradeId = 0,
                            SkillId = 5
                        },
                        new
                        {
                            Id = 80,
                            Description = "",
                            Name = "Enhanced Hammer Of The Ancients",
                            RequiredUpgradeId = 0,
                            SkillId = 6
                        },
                        new
                        {
                            Id = 81,
                            Description = "",
                            Name = "Furious Hammer Of The Ancients",
                            RequiredUpgradeId = 80,
                            SkillId = 6
                        },
                        new
                        {
                            Id = 82,
                            Description = "",
                            Name = "Violent Hammer Of The Ancients",
                            RequiredUpgradeId = 0,
                            SkillId = 6
                        },
                        new
                        {
                            Id = 83,
                            Description = "",
                            Name = "Enhanced Upheaval",
                            RequiredUpgradeId = 0,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 84,
                            Description = "",
                            Name = "Furious Upheaval",
                            RequiredUpgradeId = 83,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 85,
                            Description = "",
                            Name = "Violent Upheaval",
                            RequiredUpgradeId = 0,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 86,
                            Description = "",
                            Name = "Enhanced Double Swing",
                            RequiredUpgradeId = 0,
                            SkillId = 8
                        },
                        new
                        {
                            Id = 87,
                            Description = "",
                            Name = "Furious Double Swing",
                            RequiredUpgradeId = 86,
                            SkillId = 8
                        },
                        new
                        {
                            Id = 88,
                            Description = "",
                            Name = "Violent Double Swing",
                            RequiredUpgradeId = 0,
                            SkillId = 8
                        },
                        new
                        {
                            Id = 89,
                            Description = "",
                            Name = "Enhanced Rend",
                            RequiredUpgradeId = 0,
                            SkillId = 9
                        },
                        new
                        {
                            Id = 90,
                            Description = "",
                            Name = "Furious Rend",
                            RequiredUpgradeId = 89,
                            SkillId = 9
                        },
                        new
                        {
                            Id = 91,
                            Description = "",
                            Name = "Violent Rend",
                            RequiredUpgradeId = 0,
                            SkillId = 9
                        },
                        new
                        {
                            Id = 92,
                            Description = "",
                            Name = "Enhanced Double Stomp",
                            RequiredUpgradeId = 0,
                            SkillId = 10
                        },
                        new
                        {
                            Id = 93,
                            Description = "",
                            Name = "Strategic Double Stomp",
                            RequiredUpgradeId = 92,
                            SkillId = 10
                        },
                        new
                        {
                            Id = 94,
                            Description = "",
                            Name = "Tactical Double Stomp",
                            RequiredUpgradeId = 0,
                            SkillId = 10
                        },
                        new
                        {
                            Id = 95,
                            Description = "",
                            Name = "Enhanced Rallying Cry",
                            RequiredUpgradeId = 0,
                            SkillId = 11
                        },
                        new
                        {
                            Id = 96,
                            Description = "",
                            Name = "Strategic Rallying Cry",
                            RequiredUpgradeId = 95,
                            SkillId = 11
                        },
                        new
                        {
                            Id = 97,
                            Description = "",
                            Name = "Tactical Rallying Cry",
                            RequiredUpgradeId = 0,
                            SkillId = 11
                        },
                        new
                        {
                            Id = 98,
                            Description = "",
                            Name = "Enhanced Iron Skin",
                            RequiredUpgradeId = 0,
                            SkillId = 12
                        },
                        new
                        {
                            Id = 99,
                            Description = "",
                            Name = "Strategic Iron Skin",
                            RequiredUpgradeId = 98,
                            SkillId = 12
                        },
                        new
                        {
                            Id = 100,
                            Description = "",
                            Name = "Tactical Iron Skin",
                            RequiredUpgradeId = 0,
                            SkillId = 12
                        },
                        new
                        {
                            Id = 101,
                            Description = "",
                            Name = "Enhanced Challenging Shout",
                            RequiredUpgradeId = 0,
                            SkillId = 13
                        },
                        new
                        {
                            Id = 102,
                            Description = "",
                            Name = "Strategic Challenging Shout",
                            RequiredUpgradeId = 101,
                            SkillId = 13
                        },
                        new
                        {
                            Id = 103,
                            Description = "",
                            Name = "Tactical Challenging Shout",
                            RequiredUpgradeId = 0,
                            SkillId = 13
                        },
                        new
                        {
                            Id = 104,
                            Description = "",
                            Name = "Enhanced Kick",
                            RequiredUpgradeId = 0,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 105,
                            Description = "",
                            Name = "Mighty Kick",
                            RequiredUpgradeId = 104,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 106,
                            Description = "",
                            Name = "Power Kick",
                            RequiredUpgradeId = 0,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 107,
                            Description = "",
                            Name = "Enhanced War Cry",
                            RequiredUpgradeId = 0,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 108,
                            Description = "",
                            Name = "Mighty War Cry",
                            RequiredUpgradeId = 107,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 109,
                            Description = "",
                            Name = "Power War Cry",
                            RequiredUpgradeId = 0,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 110,
                            Description = "",
                            Name = "Enhanced Charge",
                            RequiredUpgradeId = 0,
                            SkillId = 16
                        },
                        new
                        {
                            Id = 111,
                            Description = "",
                            Name = "Mighty Charge",
                            RequiredUpgradeId = 110,
                            SkillId = 16
                        },
                        new
                        {
                            Id = 112,
                            Description = "",
                            Name = "Power Charge",
                            RequiredUpgradeId = 0,
                            SkillId = 16
                        },
                        new
                        {
                            Id = 113,
                            Description = "",
                            Name = "Enhanced Leap",
                            RequiredUpgradeId = 0,
                            SkillId = 17
                        },
                        new
                        {
                            Id = 114,
                            Description = "",
                            Name = "Mighty Leap",
                            RequiredUpgradeId = 113,
                            SkillId = 17
                        },
                        new
                        {
                            Id = 115,
                            Description = "",
                            Name = "Power Leap",
                            RequiredUpgradeId = 0,
                            SkillId = 17
                        },
                        new
                        {
                            Id = 116,
                            Description = "",
                            Name = "Enhanced Rupture",
                            RequiredUpgradeId = 0,
                            SkillId = 18
                        },
                        new
                        {
                            Id = 117,
                            Description = "",
                            Name = "Fighter's Rupture",
                            RequiredUpgradeId = 116,
                            SkillId = 18
                        },
                        new
                        {
                            Id = 118,
                            Description = "",
                            Name = "Warrior's Rupture",
                            RequiredUpgradeId = 0,
                            SkillId = 18
                        },
                        new
                        {
                            Id = 119,
                            Description = "",
                            Name = "Enhanced Steel Grasp",
                            RequiredUpgradeId = 0,
                            SkillId = 19
                        },
                        new
                        {
                            Id = 120,
                            Description = "",
                            Name = "Fighter's Steel Grasp",
                            RequiredUpgradeId = 119,
                            SkillId = 19
                        },
                        new
                        {
                            Id = 121,
                            Description = "",
                            Name = "Warrior's Steel Grasp",
                            RequiredUpgradeId = 0,
                            SkillId = 19
                        },
                        new
                        {
                            Id = 122,
                            Description = "",
                            Name = "Enhanced Death Blow",
                            RequiredUpgradeId = 0,
                            SkillId = 20
                        },
                        new
                        {
                            Id = 123,
                            Description = "",
                            Name = "Fighter's Death Blow",
                            RequiredUpgradeId = 122,
                            SkillId = 20
                        },
                        new
                        {
                            Id = 124,
                            Description = "",
                            Name = "Warrior's Death Blow",
                            RequiredUpgradeId = 0,
                            SkillId = 20
                        },
                        new
                        {
                            Id = 125,
                            Description = "",
                            Name = "Enhanced Mighty Blow",
                            RequiredUpgradeId = 0,
                            SkillId = 21
                        },
                        new
                        {
                            Id = 126,
                            Description = "",
                            Name = "Fighter's Mighty Blow",
                            RequiredUpgradeId = 125,
                            SkillId = 21
                        },
                        new
                        {
                            Id = 127,
                            Description = "",
                            Name = "Warrior's Mighty Blow",
                            RequiredUpgradeId = 0,
                            SkillId = 21
                        },
                        new
                        {
                            Id = 128,
                            Description = "",
                            Name = "Prime Call Of The Ancients",
                            RequiredUpgradeId = 0,
                            SkillId = 22
                        },
                        new
                        {
                            Id = 129,
                            Description = "",
                            Name = "Surpreme Call Of The Ancients",
                            RequiredUpgradeId = 128,
                            SkillId = 22
                        },
                        new
                        {
                            Id = 130,
                            Description = "",
                            Name = "Prime Iron Maelstrom",
                            RequiredUpgradeId = 0,
                            SkillId = 23
                        },
                        new
                        {
                            Id = 131,
                            Description = "",
                            Name = "Supreme Iron Maelstrom",
                            RequiredUpgradeId = 130,
                            SkillId = 23
                        },
                        new
                        {
                            Id = 132,
                            Description = "",
                            Name = "Prime Wrath of The Berserker",
                            RequiredUpgradeId = 0,
                            SkillId = 24
                        },
                        new
                        {
                            Id = 133,
                            Description = "",
                            Name = "Supreme Wrath of The Berserker",
                            RequiredUpgradeId = 132,
                            SkillId = 24
                        });
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Build", b =>
                {
                    b.HasOne("DiabloBuildTracker.Api.Models.Class", "Class")
                        .WithMany("Builds")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.BuildItem", b =>
                {
                    b.HasOne("DiabloBuildTracker.Api.Models.Build", "Build")
                        .WithMany("BuildItems")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiabloBuildTracker.Api.Models.Item", "Item")
                        .WithMany("BuildItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.BuildSkill", b =>
                {
                    b.HasOne("DiabloBuildTracker.Api.Models.Build", "Build")
                        .WithMany("BuildSkills")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiabloBuildTracker.Api.Models.Skill", "Skill")
                        .WithMany("BuildSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Skill", b =>
                {
                    b.HasOne("DiabloBuildTracker.Api.Models.Class", "Class")
                        .WithMany("Skills")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiabloBuildTracker.Api.Models.SkillCategory", "SkillCategory")
                        .WithMany("Skills")
                        .HasForeignKey("SkillCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("SkillCategory");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.SkillUpgrade", b =>
                {
                    b.HasOne("DiabloBuildTracker.Api.Models.Skill", "Skill")
                        .WithMany("SkillUpgrades")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Build", b =>
                {
                    b.Navigation("BuildItems");

                    b.Navigation("BuildSkills");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Class", b =>
                {
                    b.Navigation("Builds");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Item", b =>
                {
                    b.Navigation("BuildItems");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Skill", b =>
                {
                    b.Navigation("BuildSkills");

                    b.Navigation("SkillUpgrades");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.SkillCategory", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
