// <auto-generated />
using System;
using DiabloBuildTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiabloBuildTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120185138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.BuildItem", b =>
                {
                    b.Property<int>("BuildId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("BuildId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BuildItems");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.BuildSkill", b =>
                {
                    b.Property<int>("BuildId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("BuildId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("BuildSkills");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("MaxRank")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Build", b =>
                {
                    b.HasOne("DiabloBuildTracker.Api.Models.Class", "Class")
                        .WithMany("Builds")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.BuildItem", b =>
                {
                    b.HasOne("DiabloBuildTracker.Api.Models.Build", "Build")
                        .WithMany("BuildItems")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiabloBuildTracker.Api.Models.Item", "Item")
                        .WithMany("BuildItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.BuildSkill", b =>
                {
                    b.HasOne("DiabloBuildTracker.Api.Models.Build", "Build")
                        .WithMany("BuildSkills")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiabloBuildTracker.Api.Models.Skill", "Skill")
                        .WithMany("BuildSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Skill", b =>
                {
                    b.HasOne("DiabloBuildTracker.Api.Models.Class", "Class")
                        .WithMany("Skills")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Build", b =>
                {
                    b.Navigation("BuildItems");

                    b.Navigation("BuildSkills");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Class", b =>
                {
                    b.Navigation("Builds");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Item", b =>
                {
                    b.Navigation("BuildItems");
                });

            modelBuilder.Entity("DiabloBuildTracker.Api.Models.Skill", b =>
                {
                    b.Navigation("BuildSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
